FROM rhel
#FROM centos

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*


RUN yum -y update
RUN yum -y install openssl openssl-devel pciutils wget

RUN wget -O /tmp/bootstrap.cgi https://linux.dell.com/repo/hardware/dsu/bootstrap.cgi
RUN bash /tmp/bootstrap.cgi

RUN yum install -y srvadmin-idrac.x86_64

RUN yum -y clean all

COPY boot-from-iso.sh /boot-from-iso.sh

#ENTRYPOINT ["/opt/dell/srvadmin/bin/idracadm7"]
ENTRYPOINT ["/boot-from-iso.sh"]
